language: bash
sudo: required

matrix:
  include:
    - env: flavour=latest
      services:
        - docker
    - env: flavour=alpine
      services:
        - docker
  fast_finish: true

script:
  - if [ "$flavour" = "latest" ]; then make build-latest; else make build-alpine; fi
  - docker run -it --rm jakzal/phpqa:$flavour php /usr/local/bin/tools.php test
  - docker run -it --rm jakzal/phpqa:$flavour

after_script:
  - docker images
  - docker run -it --rm jakzal/phpqa:$flavour sh -c 'php /usr/local/bin/tools.php update-phars && diff $TOOLS_JSON.bak $TOOLS_JSON || echo -e "\033[0;91mSome tools might have new phar releases. Update tools.json.\033[0m"'

after_success:
  - [ "$TRAVIS_EVENT_TYPE" = "cron" ] && make build-nightly
